server:
    port: 9002

spring:
  application:
    name: USERS-SERVICE

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
        registerWithEureka: true
        fetchRegistry: true
    instance:
        hostname: localhost