server:
  port: 9191

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

spring:
  application:
    name: GATEWAY
  cloud:
    gateway:
      routes:
        - id: USERS-SERVICE
          uri: lb://USERS-SERVICE
          predicates:
            - Path=/users/**
          filters:
            - name: CircuitBreaker
              args:
                - name: USERS-SERVICE
                  fallbackUri: forward:/userServiceFallback
        - id: DEPARTMENT-SERVICE
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/departments/**
          filters:
            - name: CircuitBreaker
              args:
                - name: DEPARTMENT-SERVICE
                  fallbackUri: forward:/departmentServiceFallback

hystrix:
  commands:
    fallbackcommand:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000

#management:
#  endpoint:
#    web:
#      exposure:
#        include: hystrix.stream

management:
  endpoints:
    web:
      exposure:
        include: "*"
